# Generated by Django 4.2.7 on 2026-03-29 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.CharField(max_length=255, unique=True)),
                ("order_id", models.CharField(max_length=100)),
                ("amount", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("RAZORPAY", "Razorpay"),
                            ("WALLET", "Wallet"),
                            ("CREDIT_CARD", "Credit Card"),
                            ("UPI", "UPI"),
                        ],
                        default="RAZORPAY",
                        max_length=20,
                    ),
                ),
                (
                    "gateway_payment_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gateway_order_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gateway_signature",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("webhook_received", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
